### PR TITLE
adds portuguese translation

### PR DESCRIPTION
**Pull request by brunaw**
the encoding might need some fixing :/

### CODE REVIEW

**Comment by dcomtois** [comment]
Thank you so much!! No problem for the encoding, I'll have a look.

**Comment by dcomtois** [comment]
I had to adjust a few things but hopefully nothing that stands out as non-natural... You can test it if you have time and let me know if anything seems out of place:
```r
devtools::install_github("dcomtois/summarytools", ref = "dev-current")
library(summarytools)
st_options(lang = "pt")
```
Obrigado!

**Comment by brunaw** [comment]
Looks good to me! Eu que agradeço :)

**Comment by dcomtois** [comment]
I'm having a little trouble having you shown as a contributor... If you wish to be shown as such, could you pls do the following (sorry for the hassle, I've tried several ways but can't get it to work!):

1. delete your fork of summarytools and re-fork it (unless you had other changes you were working on)
2. on your fork, go into the "temp" branch and go into edit mode for the translation/pt.csv file
3. copy the content from [here](https://github.com/dcomtois/summarytools/edit/dev-current/translations/pt.csv) to your pt.csv file (or 
4. after saving the file, do a new pull request

Thx again, I'll update my Twitter post to indicate that the edits should be made in the "dev-current" branch rather than on "master" so next time someone submits a language, it won't be as bumpy!

**Comment by brunaw** [comment]
Oh, thanks! Let me know if I can help with anything else :)

**Comment by dcomtois** [comment]
Merged "manually" on 2019-03-03

**Pull request closed without merging**
